import React, { useEffect, useState } from 'react';
import { CheckCircle2, Copy, Fingerprint, MapPin, PackageCheck, ShieldCheck, XCircle } from 'lucide-react';
import { publicApi } from '../../services/api';
import { ScrapLinkLogo } from '../ui/ScrapLinkLogo';

type PublicRecord = {
  handoverId: string; lotId: string; material: string; weightKg: number; value: number; timestamp: string;
  location: { city: string; facility: string };
  payment: { mode: string; status: 'recorded' | 'unavailable' };
  confirmations: { collector: { confirmed: boolean; confirmedAt: string | null }; recycler: { confirmed: boolean; confirmedAt: string | null } };
};
type Verification = { verified: boolean; fingerprint: string; isDemo?: boolean; label?: string; record: PublicRecord };
const dateTime = (value: string | null) => value ? new Intl.DateTimeFormat('en-IN', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)) : 'Not recorded';
const money = (value: number) => new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 2 }).format(value);

export const PublicHandoverPage: React.FC<{ handoverId: string }> = ({ handoverId }) => {
  const [result, setResult] = useState<Verification | null>(null);
  const [error, setError] = useState('');
  const [copied, setCopied] = useState(false);
  useEffect(() => { let mounted = true; publicApi<Verification>(`/handovers/${encodeURIComponent(handoverId)}/verify`).then(data => { if (mounted) setResult(data); }).catch(cause => { if (mounted) setError(cause instanceof Error ? cause.message : 'This handover could not be verified.'); }); return () => { mounted = false; }; }, [handoverId]);
  const copyLink = async () => { try { await navigator.clipboard.writeText(window.location.href); setCopied(true); window.setTimeout(() => setCopied(false), 1800); } catch { setCopied(false); } };
  const record = result?.record;
  return <main className="min-h-screen bg-[#f7f7f2] px-4 py-8 text-slate-800 sm:py-12"><div className="mx-auto max-w-2xl"><div className="mb-8 flex items-center justify-between"><a href="/" aria-label="ScrapLink home"><ScrapLinkLogo/></a><span className="inline-flex items-center gap-1.5 rounded-full border border-slate-200 bg-white px-3 py-1.5 text-xs font-semibold text-slate-600"><ShieldCheck className="h-4 w-4 text-emerald-700"/>Public verification</span></div>
    <section className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><div className={`p-6 sm:p-8 ${result?.verified?'bg-emerald-50':'bg-slate-50'}`}><div className="flex items-start gap-4">{result ? (result.verified?<CheckCircle2 className="mt-1 h-8 w-8 shrink-0 text-emerald-700"/>:<XCircle className="mt-1 h-8 w-8 shrink-0 text-rose-600"/>):<Fingerprint className="mt-1 h-8 w-8 shrink-0 text-slate-400"/>}<div><p className="text-xs font-bold uppercase tracking-widest text-slate-500">Digital handover receipt</p><h1 className="mt-2 text-2xl font-black text-slate-950">{result?.verified?'Record verified':result?'Integrity check failed':'Verify a handover'}</h1><p className="mt-2 break-all font-mono text-sm text-slate-600">{handoverId}</p></div></div></div>
      <div className="space-y-6 p-6 sm:p-8">{result?.isDemo&&<div role="note" className="rounded-xl border border-amber-300 bg-amber-50 p-4 text-sm font-semibold text-amber-950">SAMPLE DATA · Simulated record. This is not a real-world transaction.</div>}{error&&<div role="alert" className="rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-800">{error}</div>}{!record&&!error&&<p className="text-sm text-slate-500">Looking up this handover in the public verification ledger…</p>}{record&&<>
        <div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{[{label:'Handover lot',value:record.lotId,icon:PackageCheck},{label:'Received weight',value:`${record.weightKg.toLocaleString('en-IN')} kg`,icon:PackageCheck},{label:'Estimated lot value',value:money(record.value),icon:Fingerprint},{label:'Handover time',value:dateTime(record.timestamp),icon:CheckCircle2}].map(({label,value,icon:Icon})=><div key={label} className="rounded-2xl bg-slate-50 p-3"><Icon className="h-4 w-4 text-emerald-700"/><p className="mt-3 text-[10px] font-semibold uppercase tracking-wide text-slate-500">{label}</p><p className="mt-1 break-words text-sm font-bold text-slate-900">{value}</p></div>)}</div>
        <div className="rounded-2xl border border-slate-200 p-4"><h2 className="font-bold text-slate-900">Materials handed over</h2><p className="mt-2 text-sm text-slate-700">{record.material}</p></div><div className="rounded-2xl border border-slate-200 p-4"><h2 className="font-bold text-slate-900">Receiving location</h2><p className="mt-2 flex items-center gap-2 text-sm text-slate-600"><MapPin className="h-4 w-4 shrink-0 text-emerald-700"/>{record.location.facility} · {record.location.city}</p><p className="mt-1 text-xs text-slate-500">General facility location only; private collection addresses are not published.</p></div>
        <div className="rounded-2xl border border-slate-200 p-4"><h2 className="font-bold text-slate-900">Payment record</h2><div className="mt-3 grid gap-2 text-sm sm:grid-cols-2"><p className="text-slate-600">Method <strong className="ml-1 capitalize text-slate-900">{record.payment.mode}</strong></p><p className="text-slate-600">Status <strong className="ml-1 capitalize text-slate-900">{record.payment.status}</strong></p></div></div>
        <div><h2 className="font-bold text-slate-900">Handover confirmations</h2><div className="mt-3 grid gap-3 sm:grid-cols-2">{(['collector','recycler'] as const).map(role=><div key={role} className="flex items-start gap-3 rounded-2xl border border-slate-200 p-4"><CheckCircle2 className={`mt-0.5 h-5 w-5 shrink-0 ${record.confirmations[role].confirmed?'text-emerald-700':'text-slate-300'}`}/><div><p className="font-semibold capitalize text-slate-900">{role} confirmation</p><p className="mt-1 text-xs text-slate-500">{record.confirmations[role].confirmed?`Confirmed · ${dateTime(record.confirmations[role].confirmedAt)}`:'Not confirmed'}</p></div></div>)}</div></div>
        <div className="rounded-2xl bg-slate-50 p-4"><div className="flex items-center justify-between gap-3"><p className="text-xs font-semibold text-slate-700">Record integrity fingerprint</p><button onClick={()=>void copyLink()} className="inline-flex shrink-0 items-center gap-1.5 rounded-lg border border-slate-200 bg-white px-2.5 py-1.5 text-xs font-semibold text-slate-600 hover:bg-slate-50"><Copy className="h-3.5 w-3.5"/>{copied?'Link copied':'Share record'}</button></div><p className="mt-2 text-xs text-slate-500">{result?.verified?"Fingerprint validated against the saved handover fields.":"Fingerprint does not match the saved handover fields."}</p><p className="mt-2 break-all font-mono text-[10px] leading-relaxed text-slate-500">{result?.fingerprint}</p></div>
      </>}</div></section><p className="mt-5 text-center text-xs leading-relaxed text-slate-500">This public page shows receipt details and confirmation status. It does not publish participant names, contact details, collector IDs, exact pickup addresses, payment amounts, or payment references.</p></div></main>;
};
