import { priceFor } from '../config/pricing.js';
import { ScrapLot } from '../models/ScrapLot.js';
import { Transaction } from '../models/Transaction.js';
import { User } from '../models/User.js';
import { AppError } from '../utils/AppError.js';

const event = (status, note, actor) => ({ status, note, actor, at: new Date() });
const ownerFilter = (request) => request.auth.role === 'collector' ? { collector: request.auth.sub } : request.auth.role === 'recycler' ? { selectedRecycler: request.auth.sub } : {};

export async function getPrice(request, response) { const { material, condition = 'clean', weightKg = '1' } = request.query; const rate = priceFor(material, condition); if (!rate) throw new AppError('Unknown material.', 400); response.json({ success: true, data: { material, condition, ratePerKg: rate, estimatedValue: Math.round(rate * Number(weightKg) * 100) / 100, updatedAt: new Date() } }); }
export async function createLot(request, response) { const { material, weightKg, condition, address, city, latitude, longitude } = request.body; const rate = priceFor(material, condition); if (!rate || !weightKg || !address || !city) throw new AppError('Material, weight, condition, address, and city are required.', 400); const images = (request.files || []).map((file) => ({ url: `/uploads/${file.filename}`, filename: file.filename, mimeType: file.mimetype })); const lot = await ScrapLot.create({ collector: request.auth.sub, material, weightKg: Number(weightKg), condition, location: { address, city, latitude: Number(latitude) || undefined, longitude: Number(longitude) || undefined }, quotedRate: rate, estimatedValue: Math.round(rate * Number(weightKg) * 100) / 100, images, tracking: [event('listed', 'Scrap lot listed for recycler matching.', request.auth.sub)] }); response.status(201).json({ success: true, data: lot }); }
export async function listLots(request, response) { const lots = await ScrapLot.find(ownerFilter(request)).populate('selectedRecycler', 'name recyclerProfile').sort({ createdAt: -1 }); response.json({ success: true, data: lots }); }
export async function lotById(request, response) { const lot = await ScrapLot.findOne({ _id: request.params.id, ...ownerFilter(request) }).populate('collector', 'name phone').populate('selectedRecycler', 'name phone recyclerProfile').populate('tracking.actor', 'name role'); if (!lot) throw new AppError('Scrap lot not found.', 404); response.json({ success: true, data: lot }); }
export async function matches(request, response) { const lot = await ScrapLot.findOne({ _id: request.params.id, collector: request.auth.sub }); if (!lot) throw new AppError('Scrap lot not found.', 404); const recyclers = await User.find({ role: 'recycler', isActive: true, 'recyclerProfile.acceptedMaterials': lot.material }).select('name phone recyclerProfile'); response.json({ success: true, data: recyclers.map((recycler) => ({ id: recycler.id, name: recycler.recyclerProfile.facilityName || recycler.name, phone: recycler.phone, location: recycler.recyclerProfile.location, matchScore: 92, offeredRate: priceFor(lot.material, lot.condition) })) }); }
export async function updateTracking(request, response) { const { status, note } = request.body; if (request.auth.role !== 'collector' || status !== 'cancelled' || !String(note || '').trim()) throw new AppError('Collectors can only cancel their own listed lots with a reason.', 403); const lot = await ScrapLot.findOneAndUpdate({ _id: request.params.id, collector: request.auth.sub, status: 'listed' }, { $set: { status: 'cancelled' }, $push: { tracking: event('cancelled', String(note).trim().slice(0, 500), request.auth.sub) } }, { new: true }); if (!lot) throw new AppError('Only your currently listed lots can be cancelled.', 409); response.json({ success: true, data: lot }); }
export async function transactions(request, response) { const records = await Transaction.find(request.auth.role === 'collector' ? { collector: request.auth.sub } : request.auth.role === 'recycler' ? { recycler: request.auth.sub } : {}).populate('lot', 'material weightKg status').populate('collector', 'name').populate('recycler', 'name recyclerProfile').sort({ createdAt: -1 }); response.json({ success: true, data: records }); }
