import React, { useCallback, useEffect, useState } from 'react';
import { Check, X } from 'lucide-react';
import { api } from '../../services/api';

type Offer = { _id: string; amount: number; status: string; note?: string; lot?: { material: string; weightKg: number; location: { city: string; address: string } }; recycler?: { name: string; recyclerProfile?: { facilityName?: string } } };
const labels: Record<string, string> = { paper: 'Paper', cardboard: 'Cardboard', pet_plastic: 'PET plastic', hdpe: 'HDPE plastic', metal: 'Metal', aluminium: 'Aluminium', copper: 'Copper', e_waste: 'E-waste', glass: 'Glass' };

export const RecyclerOfferInbox: React.FC = () => {
  const [offers, setOffers] = useState<Offer[]>([]);
  const [error, setError] = useState('');
  const [busy, setBusy] = useState('');
  const load = useCallback(async () => { try { const result = await api<{ data: Offer[] }>('/offers'); setOffers(result.data); setError(''); } catch (e) { setError(e instanceof Error ? e.message : 'Could not load recycler offers.'); } }, []);
  useEffect(() => { void load(); }, [load]);
  useEffect(() => { const refresh = () => void load(); window.addEventListener('platform:update', refresh); return () => window.removeEventListener('platform:update', refresh); }, [load]);
  const respond = async (offer: Offer, action: 'accept' | 'decline') => { setBusy(offer._id); setError(''); try { await api(`/offers/${offer._id}/${action}`, { method: 'POST' }); await load(); } catch (e) { setError(e instanceof Error ? e.message : 'Could not update offer.'); } finally { setBusy(''); } };
  return <section className="mt-6 overflow-hidden rounded-2xl border border-indigo-100 bg-white"><div className="border-b border-slate-100 px-5 py-4"><h2 className="font-bold text-slate-900">Recycler offers on your lots</h2><p className="mt-1 text-xs text-slate-500">Accept one offer to match a listed lot. Other pending offers on that lot will close automatically.</p></div>{error&&<p role="alert" className="px-5 py-3 text-xs text-rose-700">{error}</p>}{offers.length===0?<p className="p-6 text-sm text-slate-500">No recycler offers yet.</p>:<div className="divide-y divide-slate-100">{offers.map(offer=>{const facility=offer.recycler?.recyclerProfile?.facilityName||offer.recycler?.name||'Recycler';const pending=offer.status==='pending';const statusLabel=offer.status.replaceAll('_',' ');return <div key={offer._id} className="flex flex-col gap-4 p-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-bold text-slate-900">{facility} offers ₹{offer.amount.toLocaleString('en-IN')}</p><p className="mt-1 text-xs text-slate-600">{labels[offer.lot?.material||'']||offer.lot?.material} · {offer.lot?.weightKg} kg · {offer.lot?.location.city}</p><p className="mt-1 text-xs text-slate-500">{offer.lot?.location.address}{offer.note?` · ${offer.note}`:''}</p><span className={`mt-2 inline-flex rounded-full px-2.5 py-1 text-[11px] font-semibold capitalize ${pending?'bg-amber-50 text-amber-800':offer.status==='accepted'||offer.status==='pickup_scheduled'?'bg-blue-50 text-blue-800':offer.status==='received'?'bg-emerald-50 text-emerald-800':'bg-slate-100 text-slate-600'}`}>{statusLabel}</span></div>{pending&&<div className="flex gap-2"><button disabled={busy===offer._id} onClick={()=>void respond(offer,'decline')} className="inline-flex min-h-11 items-center gap-1 rounded-xl border border-slate-200 px-3 py-2 text-xs font-semibold text-slate-700 hover:bg-slate-50 disabled:opacity-50"><X className="h-3.5 w-3.5"/>Decline</button><button disabled={busy===offer._id} onClick={()=>void respond(offer,'accept')} className="inline-flex min-h-11 items-center gap-1 rounded-xl bg-emerald-700 px-3 py-2 text-xs font-bold text-white hover:bg-emerald-800 disabled:opacity-50"><Check className="h-3.5 w-3.5"/>Accept offer</button></div>}</div>;})}</div>}</section>;
};
