import React, { useEffect, useMemo, useState } from 'react';
import { Search, Plus, Pencil, Trash2, X, MapPin, TrendingUp, Database } from 'lucide-react';
import { CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { useApp } from '../../context/AppContext';
import { Material, Price } from '../../types';
import { api } from '../../services/api';

const INR = new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 1 });
export const PriceBoard: React.FC = () => {
  const { role } = useApp();
  const canEdit = role === 'admin';
  const [materials, setMaterials] = useState<Material[]>([]);
  const [prices, setPrices] = useState<Price[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [query, setQuery] = useState('');
  const [category, setCategory] = useState('All categories');
  const [location, setLocation] = useState('All locations');
  const [min, setMin] = useState('');
  const [max, setMax] = useState('');
  const [selected, setSelected] = useState('');
  const [editing, setEditing] = useState<Material | null>(null);
  const [showForm, setShowForm] = useState(false);
  const [form, setForm] = useState({ name: '', category: 'Plastic', amount: '', location: '', unit: 'kg' });
  const refresh = async () => { setLoading(true); try { const data = await api<{ materials: Material[]; prices: Price[] }>('/catalog'); setMaterials(data.materials); setPrices(data.prices); setSelected((current) => current || data.materials[0]?.id || ''); setError(''); } catch (e) { setError(e instanceof Error ? e.message : 'Could not load saved market data.'); } finally { setLoading(false); } };
  useEffect(() => { void refresh(); }, []);
  const latest = useMemo(() => materials.map(material => ({ material, price: prices.filter(p => p.materialId === material.id).sort((a,b) => b.date.localeCompare(a.date))[0] })).filter(row => row.price), [materials, prices]);
  const categories = ['All categories', ...Array.from(new Set(materials.map(m => m.category)))];
  const locations = ['All locations', ...Array.from(new Set(prices.map(p => p.location)))];
  const rows = latest.filter(({ material, price }) => material.name.toLowerCase().includes(query.toLowerCase()) && (category === 'All categories' || material.category === category) && (location === 'All locations' || price.location === location) && (min === '' || price.amount >= Number(min)) && (max === '' || price.amount <= Number(max)));
  const selectedMaterial = materials.find(m => m.id === selected) || rows[0]?.material || materials[0];
  const history = selectedMaterial ? prices.filter(p => p.materialId === selectedMaterial.id).sort((a,b) => a.date.localeCompare(b.date)).map(p => ({ ...p, label: new Date(`${p.date}T00:00:00`).toLocaleDateString('en-IN', { day: 'numeric', month: 'short' }) })) : [];
  const submit = async (e: React.FormEvent) => { e.preventDefault(); setError(''); if (!form.name.trim() || !Number(form.amount) || !form.location.trim()) return; try { let id = editing?.id; if (editing) await api(`/admin/materials/${encodeURIComponent(editing.id)}`, { method: 'PATCH', body: JSON.stringify({ name: form.name.trim(), category: form.category, unit: form.unit }) }); else { const created = await api<Material>('/admin/materials', { method: 'POST', body: JSON.stringify({ name: form.name.trim(), category: form.category, unit: form.unit }) }); id = created.id; } await api('/admin/prices', { method: 'POST', body: JSON.stringify({ materialId: id, amount: Number(form.amount), location: form.location.trim() }) }); await refresh(); if (id) setSelected(id); setShowForm(false); setEditing(null); setForm({ name: '', category: 'Plastic', amount: '', location: '', unit: 'kg' }); } catch (e) { setError(e instanceof Error ? e.message : 'Could not save this market record.'); } };
  const startEdit = (m: Material, amount: number, loc: string) => { setEditing(m); setForm({ name: m.name, category: m.category, amount: String(amount), location: loc, unit: m.unit }); setShowForm(true); };

  return <section className="min-h-[calc(100vh-4rem)] bg-[#f7f7f2] py-8"><div className="mx-auto max-w-7xl space-y-6 px-4 sm:px-6 lg:px-8">
    <header className="flex flex-col justify-between gap-4 rounded-3xl border border-[#dfe5dc] bg-white p-6 sm:flex-row sm:items-center sm:p-8"><div><div className="mb-2 flex items-center gap-2 text-xs font-bold uppercase tracking-widest text-emerald-800"><TrendingUp className="h-4 w-4"/> Market rates</div><h1 className="text-3xl font-black text-slate-900">Material price board</h1><p className="mt-2 max-w-2xl text-sm text-slate-500">Compare saved market prices and review their recorded history.</p></div><div className="flex items-center gap-2 rounded-xl border border-emerald-200 bg-emerald-50 px-3 py-2 text-xs font-semibold text-emerald-900"><Database className="h-4 w-4"/> MongoDB records</div></header>
    {error && <p role="alert" className="rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-800">{error}</p>}
    {canEdit && <div className="flex justify-end"><button onClick={() => { setEditing(null); setForm({ name: '', category: 'Plastic', amount: '', location: '', unit: 'kg' }); setShowForm(true); }} className="inline-flex items-center gap-2 rounded-xl bg-[#173d35] px-4 py-2.5 text-sm font-bold text-white"><Plus className="h-4 w-4"/> Add material / price</button></div>}
    <div className="grid gap-6 lg:grid-cols-[1.3fr_.7fr]">
      <div className="overflow-hidden rounded-3xl border border-[#dfe5dc] bg-white"><div className="grid gap-3 border-b border-slate-100 p-5 sm:grid-cols-2 lg:grid-cols-5"><label className="relative sm:col-span-2 lg:col-span-1"><Search className="absolute left-3 top-3 h-4 w-4 text-slate-400"/><input aria-label="Search materials" placeholder="Search material" value={query} onChange={e=>setQuery(e.target.value)} className="clean-input w-full pl-9"/></label><select aria-label="Category" className="clean-input" value={category} onChange={e=>setCategory(e.target.value)}>{categories.map(c=><option key={c}>{c}</option>)}</select><select aria-label="Location" className="clean-input" value={location} onChange={e=>setLocation(e.target.value)}>{locations.map(c=><option key={c}>{c}</option>)}</select><input aria-label="Minimum price" type="number" placeholder="Min ₹/kg" value={min} onChange={e=>setMin(e.target.value)} className="clean-input"/><input aria-label="Maximum price" type="number" placeholder="Max ₹/kg" value={max} onChange={e=>setMax(e.target.value)} className="clean-input"/></div>
        <div className="divide-y divide-slate-100">{loading ? <div className="p-10 text-center text-sm text-slate-500" role="status">Loading saved prices…</div> : rows.map(({material,price}) => { const prior=prices.filter(p=>p.materialId===material.id).sort((a,b)=>b.date.localeCompare(a.date))[1]; const delta=prior ? price.amount-prior.amount : 0; return <div key={material.id} onClick={()=>setSelected(material.id)} className={`flex cursor-pointer items-center justify-between gap-3 px-5 py-4 transition hover:bg-emerald-50/50 ${selected===material.id?'bg-emerald-50/70':''}`}><div className="min-w-0"><div className="truncate font-bold text-slate-900">{material.name}</div><div className="mt-1 flex items-center gap-2 text-xs text-slate-500"><span className="rounded-md bg-slate-100 px-2 py-0.5">{material.category}</span><MapPin className="h-3 w-3"/>{price.location} · {new Date(`${price.date}T00:00:00`).toLocaleDateString('en-IN')}</div></div><div className="shrink-0 text-right"><div className="font-mono text-lg font-bold text-slate-900">{INR.format(price.amount)}<span className="text-xs font-normal text-slate-500">/{material.unit}</span></div><div className={`text-xs font-semibold ${delta>0?'text-emerald-700':delta<0?'text-rose-600':'text-slate-400'}`}>{delta>0?'▲':delta<0?'▼':'•'} {prior ? `${INR.format(Math.abs(delta))} vs prior` : 'First observation'}</div></div>{canEdit&&<div className="flex gap-1"><button aria-label={`Edit ${material.name}`} onClick={e=>{e.stopPropagation();startEdit(material,price.amount,price.location)}} className="rounded-lg p-2 text-slate-500 hover:bg-slate-100"><Pencil className="h-4 w-4"/></button><button aria-label={`Delete ${material.name}`} onClick={e=>{e.stopPropagation(); void api(`/admin/materials/${encodeURIComponent(material.id)}`, { method: 'DELETE' }).then(refresh).catch(err=>setError(err instanceof Error ? err.message : 'Could not delete material.'));}} className="rounded-lg p-2 text-slate-500 hover:bg-rose-50 hover:text-rose-600"><Trash2 className="h-4 w-4"/></button></div>}</div>; })}{!loading&&rows.length===0&&<div className="p-10 text-center text-sm text-slate-500">{materials.length ? 'No prices match these filters.' : 'No saved materials or price observations yet.'}</div>}</div>
      </div>
      <aside className="rounded-3xl border border-[#dfe5dc] bg-white p-5 sm:p-6"><div className="flex items-start justify-between"><div><div className="text-xs font-semibold uppercase tracking-wider text-slate-400">Saved price history</div><h2 className="mt-1 text-lg font-bold text-slate-900">{selectedMaterial?.name || 'Select a material'}</h2></div><span className="rounded-lg bg-emerald-50 px-2 py-1 text-xs font-bold text-emerald-800">₹ / {selectedMaterial?.unit || 'kg'}</span></div><div className="mt-5 h-64">{history.length>0&&<ResponsiveContainer width="100%" height="100%"><LineChart data={history}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="label" tickLine={false} axisLine={false} fontSize={11}/><YAxis width={42} tickLine={false} axisLine={false} fontSize={11}/><Tooltip formatter={(value)=>INR.format(Number(value))}/><Line type="monotone" dataKey="amount" stroke="#16835d" strokeWidth={3} dot={{r:3,fill:'#16835d'}} activeDot={{r:5}}/></LineChart></ResponsiveContainer>}</div><p className="mt-2 border-t border-slate-100 pt-3 text-xs leading-relaxed text-slate-500">Rates reflect saved observations and may vary by material grade, volume and buyer.</p><h3 className="mt-5 text-sm font-bold text-slate-800">Recent observations</h3><div className="mt-2 space-y-2">{history.slice(-4).reverse().map(p=><div key={p.id} className="flex justify-between text-xs"><span className="text-slate-500">{p.label} · {p.location}</span><strong>{INR.format(p.amount)}</strong></div>)}</div></aside>
    </div>
    {!canEdit&&<p className="text-center text-xs text-slate-500">Read-only view · ask an administrator to update market observations.</p>}
  </div>
  {showForm&&<div className="fixed inset-0 z-[60] flex items-center justify-center bg-slate-950/50 p-4" role="dialog" aria-modal="true" aria-labelledby="price-form-title"><form onSubmit={submit} className="w-full max-w-lg space-y-4 rounded-3xl bg-white p-6 shadow-2xl"><div className="flex items-center justify-between"><div><h2 id="price-form-title" className="text-xl font-black">{editing?'Edit material & price':'Add material & price'}</h2><p className="text-xs text-slate-500">Price is saved as a dated observation.</p></div><button type="button" aria-label="Close" onClick={()=>setShowForm(false)}><X className="h-5 w-5"/></button></div><label className="block text-xs font-semibold">Material name<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} className="clean-input mt-1 w-full"/></label><div className="grid grid-cols-2 gap-3"><label className="text-xs font-semibold">Category<select value={form.category} onChange={e=>setForm({...form,category:e.target.value})} className="clean-input mt-1 w-full">{['Plastic','Paper','Metal','E-waste','Glass','Other'].map(c=><option key={c}>{c}</option>)}</select></label><label className="text-xs font-semibold">Unit<input value={form.unit} onChange={e=>setForm({...form,unit:e.target.value})} className="clean-input mt-1 w-full"/></label><label className="text-xs font-semibold">Price (₹)<input required min="0.01" step="0.1" type="number" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})} className="clean-input mt-1 w-full"/></label><label className="text-xs font-semibold">Market location<input required value={form.location} onChange={e=>setForm({...form,location:e.target.value})} className="clean-input mt-1 w-full"/></label></div><button type="submit" disabled={loading} className="w-full rounded-xl bg-[#173d35] py-3 text-sm font-bold text-white disabled:opacity-60">Save market record</button></form></div>}
  </section>;
};
